In [3]:
import numpy as np
import matplotlib.pyplot as pp

In [11]:
a = np.array([3, 4, 5, 6])
a.dtype, a.shape, a.size

(dtype('int64'), (4,), 4)

In [12]:
a = np.array([3.0, 4.0, 5.0, 6.0], dtype=np.float64)
a.dtype, a.shape, a.size

(dtype('float64'), (4,), 4)

In [14]:
a = np.array([[3, 4, 5, 6], [4, 5, 2, 3]], dtype=np.float64)
a.dtype, a.shape, a.size

(dtype('float64'), (2, 4), 8)

In [15]:
a = np.array([[3, 4, 5, 6], [4, 5]], dtype=np.float64)
a.dtype, a.shape, a.size

ValueError: setting an array element with a sequence.

In [23]:
np.arange(5, 100, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [26]:
np.linspace(5, 100, 5, dtype='i')

array([  5,  28,  52,  76, 100], dtype=int32)

In [35]:
a = np.random.randint(2,10, (5, 5)) 

array([[2, 3, 8, 3, 8],
       [4, 9, 4, 4, 2],
       [3, 5, 5, 8, 9],
       [2, 5, 8, 6, 3],
       [2, 5, 7, 3, 9]])

In [36]:
a.transpose()

array([[ 3.,  4.],
       [ 4.,  5.],
       [ 5.,  2.],
       [ 6.,  3.]])

In [43]:
np.save('')